services:
  nacos:
    image: registry.cn-hangzhou.aliyuncs.com/expservice-k8s/nacos-server:v2.3.2-slim
    container_name: nacos
    ports:
      - "8848:8848"
      - "9849:9848"
      - "9555:9555"
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2048k"
        max-file: 10
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: xxxxx
      MYSQL_SERVICE_USER: root@scrm
      MYSQL_SERVICE_PASSWORD: xxxxx
      MYSQL_SERVICE_PORT: 2886
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      JVM_XMS: 256m
      JVM_XMX: 512m
      JVM_XMN: 256m
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE: true
